# Generated by Django 4.1.10 on 2023-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='uploaded_images'),
        ),
    ]
